### Python Pandas Tutorials- Part 1
In Part we are going to learn about
<ol>
<li>Pandas Dataframe</li>
<li>Pandas Series</li>
<li>Pandas Basic Operations</li>
</ol>

In [1]:
!pip install pandas

In [2]:
import pandas as pd
import numpy as np


In [3]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [41]:
## create Dataframe

df=pd.DataFrame(data=np.arange(0,20).reshape(5,4),index=["Row1","Row2","Row3","Row4","Row5"],columns=["column1","column2","column3","column4"])

In [42]:
df

column1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [9]:
df.head() ## Show by default top 5 row from heading

column1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [10]:
df.tail() ## Show by default botton 5 row from heading

column1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [11]:
type(df)

pandas.core.frame.DataFrame

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   column1  5 non-null      int32
 1   column2  5 non-null      int32
 2   column3  5 non-null      int32
 3   column4  5 non-null      int32
dtypes: int32(4)
memory usage: 120.0+ bytes


In [13]:
df.describe()

column1    column2    column3    column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

##### Indexing
- columnname, rowindex[loc], rowindex columnindex number[.iloc] (3 methods are using to find indexing)


In [16]:
df.head()

column1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [17]:
### Using Column Name to find column data from all row
df['column1']

Row1     0
Row2     4
Row3     8
Row4    12
Row5    16
Name: column1, dtype: int32

In [18]:
type(df['column1']) ## if we're using one row or one column the its is called Series Type

pandas.core.series.Series

In [21]:
df[['column1','column2','column3']]

column1  column2  column3
Row1        0        1        2
Row2        4        5        6
Row3        8        9       10
Row4       12       13       14
Row5       16       17       18

In [23]:
##using row index name loc to find all data from all column
df.loc[['Row3','Row4']]

column1  column2  column3  column4
Row3        8        9       10       11
Row4       12       13       14       15

In [24]:
df.head()

column1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [26]:
df.iloc[2:4,1:3]

column2  column3
Row3        9       10
Row4       13       14

In [27]:
df.iloc[2:,1:]

column2  column3  column4
Row3        9       10       11
Row4       13       14       15
Row5       17       18       19

In [28]:
df.head(
)

column1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [29]:
df.iloc[:,0::3]

column1  column4
Row1        0        3
Row2        4        7
Row3        8       11
Row4       12       15
Row5       16       19

In [31]:
##convert dataframe into arrays
df.iloc[:].values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [32]:
## Basic operations
df.isnull().sum()


column1    0
column2    0
column3    0
column4    0
dtype: int64

In [33]:
df

column1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [34]:


df=pd.DataFrame(data=[[1,np.nan,3],[1,8,9]],index=["Row1","Row2"],columns=["column1","column2","column3"])

In [35]:
df

column1  column2  column3
Row1        1      NaN        3
Row2        1      8.0        9

In [36]:
df.isnull().sum()

column1    0
column2    1
column3    0
dtype: int64

In [37]:
df.isnull().sum()==0

column1     True
column2    False
column3     True
dtype: bool

In [39]:
df['column3'].value_counts()

9    1
3    1
Name: column3, dtype: int64

In [40]:
df

column1  column2  column3
Row1        1      NaN        3
Row2        1      8.0        9

In [43]:
df

column1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [45]:
df['column2'].unique(
)

array([ 1,  5,  9, 13, 17])

In [46]:
df[df['column2']>2]

column1  column2  column3  column4
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19