## Python Numpy Arrays

### numpy methods and attributes (Search on Google for helpinf regarding methods and attributions)

### Numpy Tutorials
- NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

### What is an array
- An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data 

In [2]:
import numpy as np

In [3]:
lst =[1,2,3,4,5]
arr=np.array(lst)

In [5]:
print(arr)

[1 2 3 4 5]


In [6]:
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[3,4,5,6,7]

arr1=np.array([lst1,lst2,lst3])

In [8]:
print(arr1)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]


In [9]:
arr1.shape

(3, 5)

In [10]:
arr

array([1, 2, 3, 4, 5])

In [11]:
#indexing
arr[3]

4

In [12]:
arr[3]=5

In [13]:
arr

array([1, 2, 3, 5, 5])

In [14]:
arr[-1]

5

In [20]:
arr[::-3]

array([5, 2])

In [21]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [48]:
arr1[0:,0::4]

array([[1, 5],
       [2, 6],
       [3, 7]])

In [22]:
arr1.shape

(3, 5)

In [23]:
arr1[:,1]

array([2, 3, 4])

In [24]:
arr1[1:,1:3]



array([[3, 4],
       [4, 5]])

In [25]:
arr1[1:,3:]

array([[5, 6],
       [6, 7]])

In [26]:
##EDA
arr

array([1, 2, 3, 5, 5])

In [28]:
arr[3]=4

In [29]:
arr

array([1, 2, 3, 4, 5])

In [31]:
arr[arr<4]

array([1, 2, 3])

In [32]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [33]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [35]:
##mechanism to create an array
np.arange(1,20,2).reshape(2,5,1)

array([[[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9]],

       [[11],
        [13],
        [15],
        [17],
        [19]]])

In [36]:

arr *arr

array([ 1,  4,  9, 16, 25])

In [37]:
arr1 * arr1

array([[ 1,  4,  9, 16, 25],
       [ 4,  9, 16, 25, 36],
       [ 9, 16, 25, 36, 49]])

In [39]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [42]:
np.random.randint(10,50,4).reshape(2,2)


array([[48, 43],
       [20, 22]])

In [43]:
    np.random.randn1(5,6)

array([[ 1.56665330e+00,  1.55539924e+00,  6.36297912e-01,
         3.84172333e-01,  1.00435536e+00, -9.21517267e-01],
       [ 1.46138903e-04,  1.89333076e-01, -5.21058275e-03,
         4.59412127e-01,  7.82186958e-01,  1.60398377e-01],
       [ 2.03052172e-01,  1.36993843e-01,  8.31182643e-01,
         6.96244237e-02, -4.03308402e-01, -4.78093828e-01],
       [ 8.30646387e-01, -4.69242262e-01,  7.49840723e-01,
        -2.00222940e+00,  4.44115123e-02,  1.17180111e+00],
       [-1.69100204e+00,  3.98172042e-01, -1.24365407e+00,
         1.63771036e+00, -2.62998528e-01,  6.43990025e-01]])

In [44]:
np.random.random_sample((4,7)) #sample random between (0.0 to 1.0)

array([[0.19224979, 0.32082137, 0.76186528, 0.9410542 , 0.79932526,
        0.23639459, 0.83422215],
       [0.72290545, 0.67253342, 0.69580055, 0.05993596, 0.86745807,
        0.75814094, 0.07632161],
       [0.28253609, 0.29831467, 0.10555728, 0.6707277 , 0.96747968,
        0.7896662 , 0.02894733],
       [0.79352102, 0.56242736, 0.5189846 , 0.05633833, 0.55004996,
        0.28277054, 0.26905177]])